--------------------------------------------------------
--  File created - Thursday-June-11-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "T3"."TBL_ACCOUNTS" 
   (	"ID" VARCHAR2(10 BYTE), 
	"FIRST_NAME" VARCHAR2(255 BYTE), 
	"MIDDLE_NAME" VARCHAR2(255 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"GENDER" VARCHAR2(255 BYTE), 
	"USER_LEVEL" VARCHAR2(255 BYTE), 
	"CREATED_AT" DATE, 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into T3.TBL_ACCOUNTS
SET DEFINE OFF;
Insert into T3.TBL_ACCOUNTS (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,GENDER,USER_LEVEL,CREATED_AT,USERNAME,PASSWORD) values ('23','Diether',null,'Llenares','Male','Admin',to_date('06/10/2020 09:21:10','MM/DD/RRRR HH24:MI:SS'),'DaddyDitz','titer');
Insert into T3.TBL_ACCOUNTS (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,GENDER,USER_LEVEL,CREATED_AT,USERNAME,PASSWORD) values ('24','Martin',null,'Chu','Male','Admin',to_date('06/10/2020 09:24:11','MM/DD/RRRR HH24:MI:SS'),'martin','martin');
Insert into T3.TBL_ACCOUNTS (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,GENDER,USER_LEVEL,CREATED_AT,USERNAME,PASSWORD) values ('32','Erron','Tompong','Bacani','male','manager',to_date('06/10/2020 15:37:58','MM/DD/RRRR HH24:MI:SS'),'erron.bacani','welcome');
Insert into T3.TBL_ACCOUNTS (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,GENDER,USER_LEVEL,CREATED_AT,USERNAME,PASSWORD) values ('1','Renz Martin','Chu','Cerico','Male','Admin',to_date('06/09/2020 14:39:00','MM/DD/RRRR HH24:MI:SS'),'renz.cerico','rmCerico');
Insert into T3.TBL_ACCOUNTS (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,GENDER,USER_LEVEL,CREATED_AT,USERNAME,PASSWORD) values ('33','Dha',null,'Antonio','female','supervisor',to_date('06/10/2020 15:39:31','MM/DD/RRRR HH24:MI:SS'),'dha','welcome');
--------------------------------------------------------
--  DDL for Index TBL_ACCOUNTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T3"."TBL_ACCOUNTS_PK" ON "T3"."TBL_ACCOUNTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ACCOUNTS_AUTO_INC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "T3"."ACCOUNTS_AUTO_INC" 
   before insert on "T3"."TBL_ACCOUNTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select ACCOUNTS_AUTO_INC.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "T3"."ACCOUNTS_AUTO_INC" ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "T3"."TBL_ACCOUNTS" ADD CONSTRAINT "TBL_ACCOUNTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "T3"."TBL_ACCOUNTS" MODIFY ("USER_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_ACCOUNTS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_ACCOUNTS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_ACCOUNTS" MODIFY ("ID" NOT NULL ENABLE);
