--------------------------------------------------------
--  File created - Monday-June-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_ACTIVITY_DOWNTIME
--------------------------------------------------------

  CREATE TABLE "T3"."TBL_ACTIVITY_DOWNTIME" 
   (	"ID" NUMBER(10,0), 
	"DOWNTIME_TYPE_ID" NUMBER(10,0), 
	"MINUTES" NUMBER(10,0), 
	"REMARKS" VARCHAR2(255 BYTE), 
	"QUANTITY" NUMBER(10,0), 
	"ACTIVITY_ID" NUMBER(10,0), 
	"CREATED_BY" NUMBER(10,0), 
	"CREATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into T3.TBL_ACTIVITY_DOWNTIME
SET DEFINE OFF;
Insert into T3.TBL_ACTIVITY_DOWNTIME (ID,DOWNTIME_TYPE_ID,MINUTES,REMARKS,QUANTITY,ACTIVITY_ID,CREATED_BY,CREATED_AT) values (21,1,10,'waaaahhhhhhhh',10,361,1,to_date('08-JUN-2020 10:38:28','DD-MON-YYYY HH24:MI:SS'));
Insert into T3.TBL_ACTIVITY_DOWNTIME (ID,DOWNTIME_TYPE_ID,MINUTES,REMARKS,QUANTITY,ACTIVITY_ID,CREATED_BY,CREATED_AT) values (2,2,10,'LALALALELELE',10,351,1,null);
Insert into T3.TBL_ACTIVITY_DOWNTIME (ID,DOWNTIME_TYPE_ID,MINUTES,REMARKS,QUANTITY,ACTIVITY_ID,CREATED_BY,CREATED_AT) values (3,1,10,'BLEEEE',20,351,1,to_date('16-MAR-2020 15:36:03','DD-MON-YYYY HH24:MI:SS'));
Insert into T3.TBL_ACTIVITY_DOWNTIME (ID,DOWNTIME_TYPE_ID,MINUTES,REMARKS,QUANTITY,ACTIVITY_ID,CREATED_BY,CREATED_AT) values (4,1,10,'LALALA',50,349,1,to_date('16-MAR-2020 15:48:29','DD-MON-YYYY HH24:MI:SS'));
Insert into T3.TBL_ACTIVITY_DOWNTIME (ID,DOWNTIME_TYPE_ID,MINUTES,REMARKS,QUANTITY,ACTIVITY_ID,CREATED_BY,CREATED_AT) values (5,2,15,'WOOOF',20,349,1,to_date('16-MAR-2020 15:54:38','DD-MON-YYYY HH24:MI:SS'));
--------------------------------------------------------
--  DDL for Index TBL_ACTIVITY_DOWNTIME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T3"."TBL_ACTIVITY_DOWNTIME_PK" ON "T3"."TBL_ACTIVITY_DOWNTIME" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TBL_ACTIVITY_DOWNTIME_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "T3"."TBL_ACTIVITY_DOWNTIME_TRG" 
BEFORE INSERT ON TBL_ACTIVITY_DOWNTIME 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "T3"."TBL_ACTIVITY_DOWNTIME_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_ACTIVITY_DOWNTIME_PK_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "T3"."TBL_ACTIVITY_DOWNTIME_PK_TRG" 
   before insert on "T3"."TBL_ACTIVITY_DOWNTIME" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select TBL_ACTIVITY_DOWNTIME_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "T3"."TBL_ACTIVITY_DOWNTIME_PK_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_ACTIVITY_DOWNTIME
--------------------------------------------------------

  ALTER TABLE "T3"."TBL_ACTIVITY_DOWNTIME" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_ACTIVITY_DOWNTIME" MODIFY ("ACTIVITY_ID" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_ACTIVITY_DOWNTIME" ADD CONSTRAINT "TBL_ACTIVITY_DOWNTIME_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "T3"."TBL_ACTIVITY_DOWNTIME" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_ACTIVITY_DOWNTIME" MODIFY ("MINUTES" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_ACTIVITY_DOWNTIME" MODIFY ("DOWNTIME_TYPE_ID" NOT NULL ENABLE);
