--------------------------------------------------------
--  File created - Monday-June-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_DOWNTIME_TYPES
--------------------------------------------------------

  CREATE TABLE "T3"."TBL_DOWNTIME_TYPES" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"DEFAULT_MINUTES" NUMBER(10,0), 
	"QUANTITY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into T3.TBL_DOWNTIME_TYPES
SET DEFINE OFF;
Insert into T3.TBL_DOWNTIME_TYPES (ID,NAME,DEFAULT_MINUTES,QUANTITY) values (1,'downtime 1',10,null);
Insert into T3.TBL_DOWNTIME_TYPES (ID,NAME,DEFAULT_MINUTES,QUANTITY) values (2,'downtime 2',15,null);
Insert into T3.TBL_DOWNTIME_TYPES (ID,NAME,DEFAULT_MINUTES,QUANTITY) values (3,'downtime 3',20,null);
--------------------------------------------------------
--  DDL for Index DOWNTIME_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T3"."DOWNTIME_TYPES_PK" ON "T3"."TBL_DOWNTIME_TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger DOWNTIME_TYPES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "T3"."DOWNTIME_TYPES_TRG" 
BEFORE INSERT ON TBL_DOWNTIME_TYPES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "T3"."DOWNTIME_TYPES_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DOWNTIME_TYPES
--------------------------------------------------------

  ALTER TABLE "T3"."TBL_DOWNTIME_TYPES" ADD CONSTRAINT "DOWNTIME_TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "T3"."TBL_DOWNTIME_TYPES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_DOWNTIME_TYPES" MODIFY ("ID" NOT NULL ENABLE);
