--------------------------------------------------------
--  File created - Monday-June-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_MANPOWER
--------------------------------------------------------

  CREATE TABLE "T3"."TBL_MANPOWER" 
   (	"ID" NUMBER(10,0), 
	"POSITION_ID" NUMBER(10,0), 
	"MANPOWER_ID" NUMBER(10,0), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"REMARKS" VARCHAR2(255 BYTE), 
	"LAST_UPDATED_BY" NUMBER(10,0), 
	"DATE_ENTERED" DATE, 
	"DATE_UPDATED" DATE, 
	"HEADER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into T3.TBL_MANPOWER
SET DEFINE OFF;
Insert into T3.TBL_MANPOWER (ID,POSITION_ID,MANPOWER_ID,START_TIME,END_TIME,REMARKS,LAST_UPDATED_BY,DATE_ENTERED,DATE_UPDATED,HEADER_ID) values (121,1,1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),'REMARKS',1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),181);
Insert into T3.TBL_MANPOWER (ID,POSITION_ID,MANPOWER_ID,START_TIME,END_TIME,REMARKS,LAST_UPDATED_BY,DATE_ENTERED,DATE_UPDATED,HEADER_ID) values (122,1,1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),'REMARKS',1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),181);
Insert into T3.TBL_MANPOWER (ID,POSITION_ID,MANPOWER_ID,START_TIME,END_TIME,REMARKS,LAST_UPDATED_BY,DATE_ENTERED,DATE_UPDATED,HEADER_ID) values (65,1,1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),'REMARKS',1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),143);
Insert into T3.TBL_MANPOWER (ID,POSITION_ID,MANPOWER_ID,START_TIME,END_TIME,REMARKS,LAST_UPDATED_BY,DATE_ENTERED,DATE_UPDATED,HEADER_ID) values (66,1,1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),'REMARKS',1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),143);
Insert into T3.TBL_MANPOWER (ID,POSITION_ID,MANPOWER_ID,START_TIME,END_TIME,REMARKS,LAST_UPDATED_BY,DATE_ENTERED,DATE_UPDATED,HEADER_ID) values (67,1,1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),'REMARKS',1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),144);
Insert into T3.TBL_MANPOWER (ID,POSITION_ID,MANPOWER_ID,START_TIME,END_TIME,REMARKS,LAST_UPDATED_BY,DATE_ENTERED,DATE_UPDATED,HEADER_ID) values (68,1,1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),'REMARKS',1,to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),to_date('29-FEB-2020 00:00:00','DD-MON-YYYY HH24:MI:SS'),144);
--------------------------------------------------------
--  DDL for Index TBL_MANPOWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T3"."TBL_MANPOWER_PK" ON "T3"."TBL_MANPOWER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TBL_MANPOWER_PK_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "T3"."TBL_MANPOWER_PK_TRIGGER" 
   before insert on "T3"."TBL_MANPOWER" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select TBL_MANPOWER_PK_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "T3"."TBL_MANPOWER_PK_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_MANPOWER
--------------------------------------------------------

  ALTER TABLE "T3"."TBL_MANPOWER" MODIFY ("HEADER_ID" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_MANPOWER" ADD CONSTRAINT "TBL_MANPOWER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "T3"."TBL_MANPOWER" MODIFY ("DATE_ENTERED" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_MANPOWER" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_MANPOWER" MODIFY ("MANPOWER_ID" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_MANPOWER" MODIFY ("POSITION_ID" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_MANPOWER" MODIFY ("ID" NOT NULL ENABLE);
