--------------------------------------------------------
--  File created - Monday-June-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_ACTIVITY_DETAILS
--------------------------------------------------------

  CREATE TABLE "T3"."TBL_ACTIVITY_DETAILS" 
   (	"ID" NUMBER(10,0), 
	"ACTIVITY_ID" NUMBER(10,0), 
	"LOT_NUMBER" VARCHAR2(255 BYTE), 
	"PACKED_QTY" NUMBER(10,0) DEFAULT 0, 
	"ADJ_QTY" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into T3.TBL_ACTIVITY_DETAILS
SET DEFINE OFF;
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (41,281,'1231313',50,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (81,1,'12313',5000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (82,321,'500',5000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (83,322,'12313',10000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (84,323,'12313',123130,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (85,325,'500',5000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (86,326,'1000',1000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (87,328,'500',1000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (25,259,'111111',48,2);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (89,333,'asdfasf',12312310,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (90,335,'asdfasf',12312310,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (91,337,'asdfasf',12312310,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (92,346,'1000',1000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (93,347,'5000',5000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (94,348,'1000',1000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (95,349,'5000',5000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (22,263,'1',2,48);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (29,257,'2222',200,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (30,257,'11111',100,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (42,281,'1231313',0,100);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (61,306,'100',200,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (88,331,'asdfasf',12312310,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (101,361,'23414124',1000,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (26,259,'111111',500,500);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (27,258,'6555565656',100,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (28,259,'111111',500,500);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (1,107,'14110119',37,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (2,107,'14110119',79,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (3,107,'14110119',51,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (4,107,'14110119',178,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (5,107,'14110119',42,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (6,107,'14110119',29,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (7,107,'14110119',60,0);
Insert into T3.TBL_ACTIVITY_DETAILS (ID,ACTIVITY_ID,LOT_NUMBER,PACKED_QTY,ADJ_QTY) values (8,107,'14110119',2074,50);
--------------------------------------------------------
--  DDL for Index TBL_ACTIVITY_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T3"."TBL_ACTIVITY_DETAILS_PK" ON "T3"."TBL_ACTIVITY_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TBL_ACTIVITY_DEATILS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "T3"."TBL_ACTIVITY_DEATILS_TRIGGER" 
   before insert on "T3"."TBL_ACTIVITY_DETAILS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select TBL_ACTIVITY_DETAILS_PK_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "T3"."TBL_ACTIVITY_DEATILS_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_ACTIVITY_DETAILS
--------------------------------------------------------

  ALTER TABLE "T3"."TBL_ACTIVITY_DETAILS" ADD CONSTRAINT "TBL_ACTIVITY_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "T3"."TBL_ACTIVITY_DETAILS" MODIFY ("ADJ_QTY" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_ACTIVITY_DETAILS" MODIFY ("PACKED_QTY" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_ACTIVITY_DETAILS" MODIFY ("ACTIVITY_ID" NOT NULL ENABLE);
  ALTER TABLE "T3"."TBL_ACTIVITY_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
